### ISSUE TITLE
Баг в ленте публикаций

### ISSUE THREAD

**Issue by Takohashi** [ipshelp/russian-language#209]
Заходим в какую-нибудь ленту. В колонке «Период времени» указано «За последние 365 дней» — кликаем по этой колонке, чтобы открыть параметры, а потом ещё раз, чтобы закрыть — надпись сменяется на «За последние [object Object] дней».
В оригинале начальная надпись «Past 365 days» заменяется на «Past days».

**Comment by Takohashi** [comment]
Хотя по-хорошему в этих лентах надо бы как-то полностью переделать перевод. В английском там всё более-менее чисто, коротко и понятно. А в русском просто какой-то из громоздкости и запутанности. Например открываешь «Мои публикации» и видишь там какие-то посты от других пользователей. Только потом становится понятно, что это посты пользователей в твоих темах. В английском сразу понятно — «Content I Started»

**Comment by ilyahoilik** [comment]
> Заходим в какую-нибудь ленту. В колонке «Период времени» указано «За последние 365 дней» — кликаем по этой колонке, чтобы открыть параметры, а потом ещё раз, чтобы закрыть — надпись сменяется на «За последние [object Object] дней».

Не могу воспроизвести, видимо уже где-то кем-то было исправлено.

Да, надо привести всё в порядок.

**Comment by ilyahoilik** [comment]
Вроде привёл, в следующей версии станет доступно
