### ISSUE TITLE
Виджет подписок

### ISSUE THREAD

**Issue by TemKaSD** [ipshelp/russian-language#225]
Илья, приветствую. Хотелось бы сначала сказать, что ты большой молодец, делаешь отличные продукты для IPS.

![image](https://user-images.githubusercontent.com/6318282/94216551-01f51a80-ff23-11ea-8c71-4c12273cde1f.png)

здесь нужно изменить за первый месяц. а еще лучше, сократить это как-то. Например: 500р/мес, продление - 300р.

**Comment by ilyahoilik** [comment]
Проблема в том, что эта же строка используется и в других местах, например на странице продукта. Сокращать недели/месяца - ну не знаю, не очень хочется. Тем более в оригинале практически так же длинно. Буду думать.

**Comment by ilyahoilik** [comment]
> что ты большой молодец, делаешь отличные продукты для IPS

Спасибо :)
