### ISSUE TITLE
Ошибка - двойное двоеточие в разрешенных типах файлов

### ISSUE THREAD

**Issue by rvalitov** [ipshelp/russian-language#236]
Двойное двоеточие появляется в окне написания комментария:
![image](https://user-images.githubusercontent.com/16267156/106811974-23f46b80-6680-11eb-892f-224bf116a772.png)

Причина проблемы в том, что оригинальная надпись на английском без двоеточия, а на русском появляется двоеточие:
![image](https://user-images.githubusercontent.com/16267156/106812014-35d60e80-6680-11eb-8da9-9522abb4e2a7.png)

**Comment by ilyahoilik** [comment]
Спасибо! :)
