### ISSUE TITLE
Отсутствует индикация изменений с последнего релиза GitHub

### ISSUE THREAD

**Issue by rvalitov** [ipshelp/russian-language#240]
Добрый день! Спасибо за вашу работу и этот полезный проект перевода!
Хотелось бы, чтобы в GitHub было понятно, какие коммиты были сделаны после последнего релиза и было понимание насколько актуален последний релиз. Обычно во всех репозитариях на GitHub такая информация выводится, [пример](https://github.com/joomla/joomla-cms/releases/tag/3.9.24):
![image](https://user-images.githubusercontent.com/16267156/107001354-8b9ed980-679a-11eb-92cd-8a5374620e3d.png)

К сожалению у вас в проекте такой информации нет:
![image](https://user-images.githubusercontent.com/16267156/107001487-c3a61c80-679a-11eb-8fad-fe6e771e473a.png)

Это не позволяет с первого взгляда оценить еще незарелизенные изменения в переводе и понять актуальность последней версии.

Прошу вас выкатывать релизы с возможностью учета коммитов, если это возможно.

**Comment by ilyahoilik** [comment]
Наверное это из-за того, что я релизы привязываю к коммитам, а не к ветке. Попробую привязывать к ветке, надеюсь это поможет.

**Comment by rvalitov** [comment]
Я обычно создаю новый тэг в рамках одной ветки. И уже потом на основе этого тэга в GitHub создается релиз. Всегда работает как надо и история отображается.
