### ISSUE TITLE
Автоматизация релизов

### ISSUE THREAD

**Issue by rvalitov** [ipshelp/russian-language#242]
Спасибо Вам большое за Ваш перевод и работу!

Учитывая неочевидность #240 , обнаружил, что последний релиз был 1 октября 2020, а сейчас февраль 2021, т.е. за 4 месяца не было ни одного нового релиза, хотя за это время перевод обновлялся. Было бы очень полезно, если бы релизы появлялись чаще, по мере актуализации перевода.

Мне неизвестно каким образом вы делаете релизы. Возможно, этот процесс не автоматизирован, из-за чего релизы выходят редко. В связи с этим предлагаю автоматизацию релизов, например, с помощью https://github.com/marketplace/actions/automatic-releases

Готов оказать помощь. Буду рад узнать ваше мнение и ваши мысли на этот счет. Еще раз огромное вам спасибо за этот проект и проделанную работу!

**Comment by ilyahoilik** [comment]
Я его всё равно выгружаю из ips, на всякий случай. Поэтому здесь в автоматизации нет смысла. Долго не обновлял потому что лицензия была не активна и не было возможности её продлить.
