### ISSUE TITLE
edit_log_prune_notice

### ISSUE THREAD

**Issue by GitKira** [ipshelp/russian-language#244]
edit_log_prune_notice
`Обратите внимание, что редакции старше {# [1:day][?:days]} удаляются и больше не будут отображаться здесь.`
https://s8.hostingkartinok.com/uploads/images/2021/02/d668e1470739a94d0fc5622a0623f883.jpg

**Comment by rvalitov** [comment]
Это уже давно исправлено. Проблема в том, что версия, которая опубликована в Marketplace давно не обновлялась, и не содержит все актуальные правки. Я уже создал по этому поводу вопрос про автоматизацию релизов или хотя бы более частый выпуск релизов в Marketplace #242
