### ISSUE TITLE
can_set_best_answer

### ISSUE THREAD

**Issue by Sipsb** [ipshelp/russian-language#260]
Оригинал -- Can set best answer/solved for questions and topics?
Перевод   -- Может отмечать лучший ответ в вопросах
Обновить -- Может отмечать лучший ответ/решение для вопросов и тем

**Comment by rvalitov** [comment]
Еще бы желательно скриншот, чтобы понимать контекст. На мой взгляд "может" - это неоднозначное слово: "может", а "может и нет". Лучше заменить на "Разрешить". Как вы считаете?

**Comment by Sipsb** [comment]
ТОгда придется везде менять на **"Разрешить"**.

![2021-03-05_23-08-22](https://user-images.githubusercontent.com/22107941/110168258-f843dd00-7e07-11eb-9cbb-517290231ace.png)

**Comment by rvalitov** [comment]
Согласен. По хорошему нужно везде менять.

**Comment by ilyahoilik** [comment]
На "Разрешить" поменяем потом, там много
