### ISSUE TITLE
Отложенная запись в блоге

### ISSUE THREAD

**Issue by ilyahoilik** [ipshelp/russian-language#262]
<img width="550" alt="Снимок экрана 2021-03-10 в 11 59 00" src="https://user-images.githubusercontent.com/7265704/110603417-0d1dc900-8198-11eb-9440-a120821c376a.png">

**Comment by rvalitov** [comment]
Во что планируется переделать? Было бы удобнее понимать, когда в описании указывается что меняется на что. Потому что тогда вдруг появятся иные мысли/предложения как можно поправить.

**Comment by ilyahoilik** [comment]
Запись пользователя %s в %s опубликуется
