### ISSUE TITLE
Отсутствует перевод

### ISSUE THREAD

**Issue by Sipsb** [ipshelp/russian-language#263]
mod_confirm_visible_desc
mod_confirm_hidden_desc

**Comment by ilyahoilik** [comment]
Там пустые строки

**Comment by Sipsb** [comment]
Возможно нужно обновить IPS

![2021-03-13_17-36-45](https://user-images.githubusercontent.com/22107941/111033546-d90a0880-8422-11eb-8660-0c9162c881d2.png)
![2021-03-13_17-36-13](https://user-images.githubusercontent.com/22107941/111033549-dad3cc00-8422-11eb-9a6d-e9f6d7ca637f.png)

**Comment by ilyahoilik** [comment]
<img width="381" alt="Снимок экрана 2021-03-13 в 20 14 18" src="https://user-images.githubusercontent.com/7265704/111038188-b71b8080-8438-11eb-95f6-21c842d0e63c.png">
<img width="381" alt="Снимок экрана 2021-03-13 в 20 14 07" src="https://user-images.githubusercontent.com/7265704/111038191-b84cad80-8438-11eb-8009-5a7fc67180f5.png">
В самой последней версии таких строк нет.

**Comment by Sipsb** [comment]
Спасибо! Проблема оказалось только у меня. Удалил эти 2 ключа из БД оказалось, что это остатки предыдущих версий.

![2021-03-13_20-51-29](https://user-images.githubusercontent.com/22107941/111039328-81799600-843e-11eb-86a8-4759bfd7b77d.png)

**Comment by rvalitov** [comment]
Хм, а у меня тоже есть эти строки:
![image](https://user-images.githubusercontent.com/16267156/111039580-d964cc80-843f-11eb-8735-0f6163401a4a.png)

Почему так? Регулярно обновляюсь, разве при обновлениях старые более неиспользуемые строки не должны сами удалятся, и весь этот мусор копится получается?

**Comment by Sipsb** [comment]
Получается что да, я сейчас проверяю всю БД.

**Comment by rvalitov** [comment]
Проверил поиском по исходному коду, действительно там эти строки не фигурируют. 🤦‍♂️ 
А в БД получается есть.
Вот подстава...

**Comment by rvalitov** [comment]
Так, а для обратной совместимости с предыдущими релизами IPS 4.5.x, разве не нужно эти строки тоже иметь в русском переводе? Это я о том, что если человек устанавливает пакет русского языка к примеру не на самую свежую версию, а на предпоследнюю, то получается русский перевод у него окажется неполным? Какой здесь подход используется?

**Comment by Sipsb** [comment]
Обратной совместимости в IPS нет. Я поступил так --> Отсортировал (core_sys_lang_words - **cms**) по версии в БД и удалил, затем обновил через обновление приложения "Pages".

**Comment by rvalitov** [comment]
@Sipsb спасибо большое за информацию! Получается вы удалили все строки в БД, которые не соответствуют текущей версии IPS? А если приложение "Pages" уже последняя версия? Нельзя же форсированно обновить?
Насчет обратной совместимости я имею ввиду то, что @ilyahoilik выпускает отдельно перевод под каждую версию IPS? Или только под последнюю версию? Или единый перевод, который можно применить к любой версии IPS в рамках одного мажорного релиза, например, 4.x или 4.5.x? 

Исходя из используемого подхода появляется понимание того, должен ли перевод в рамках данного проекта содержать исключительно те строки, которые есть только в последней актуальной версии IPS, или же может содержать строки из более ранних версий. Если же ориентироваться исключительно на последний релиз, то должен быть механизм "выпиливания" старых строк (например, который вы описали), который должен применять @ilyahoilik при каждом релизе, дабы соответствовать выбранному подходу.

**Comment by ilyahoilik** [comment]
> @ilyahoilik выпускает отдельно перевод под каждую версию IPS?
Я выпускаю перевод под каждую версию https://github.com/ipshelp/russian-language/releases

> Если же ориентироваться исключительно на последний релиз, то должен быть механизм "выпиливания" старых строк (например, который вы описали), который должен применять @ilyahoilik при каждом релизе, дабы соответствовать выбранному подходу
Начиная с версии 4.5 старые строки удаляются из системы при обновлении.

**Comment by rvalitov** [comment]
@ilyahoilik спасибо большое за ответ. У меня 4.5, и я не так давно пользуюсь IPS. Более древних версий у меня установлено не было в принципе. Всё лицензионное. Соответственно обновления происходили исключительно в рамках 4.5 до новых минорных версий. Однако старые строки у меня содержатся 😕

**Comment by Sipsb** [comment]
У меня обновления с IPS 4.0 так что мусора хватает, но мне удалось почистить всё за исключением таблиц **core_**, так как нет возможности из ACP обновить "**System**". Буду пробовать метод очистки при переходе на 4.6.

**Comment by ilyahoilik** [comment]
> Соответственно обновления происходили исключительно в рамках 4.5 до новых минорных версий. Однако старые строки у меня содержатся 😕

Тогда стоит написать в поддержку Invision Community.
