### ISSUE TITLE
default_menu_item_1

### ISSUE THREAD

**Issue by Sipsb** [ipshelp/russian-language#264]
Надо бы оставить как было раньше - **Сообщество**
Сейчас переведено как - **Просмотр**

![2021-03-20_19-11-22](https://user-images.githubusercontent.com/22107941/111876556-4f24e700-89b0-11eb-94c6-ad69b22b4e9b.png)

**Comment by rvalitov** [comment]
Да, "Просмотр" тут вообще не к месту. "Сообщество" правда тоже не идеальный вариант, надо подумать...
