### ISSUE TITLE
Сообщение одобрено

### ISSUE THREAD

**Issue by ilyahoilik** [ipshelp/russian-language#267]
<img width="370" alt="Снимок экрана 2021-03-22 в 23 30 34" src="https://user-images.githubusercontent.com/7265704/112054443-a53b8b00-8b66-11eb-8c92-70efeb4ebfec.png">
Не "Сообщение одобрено", а "Премодерация" или как-то так. Отображается при включённой премодерации сообщений в теме.

**Comment by rvalitov** [comment]
Странно у меня такого нет. Выводится "Ожидает утверждения" если я смотрю на пост в форуме:
![image](https://user-images.githubusercontent.com/16267156/116304861-aede9100-a7ab-11eb-85f6-22c3a149599a.png)

Или это где-то в другом месте надо искать?

**Comment by ilyahoilik** [comment]
Это другое, включите премодерацию в теме
