### ISSUE TITLE
Ошибка в IPS отсутствие ключа

### ISSUE THREAD

**Issue by Sipsb** [ipshelp/russian-language#268]
/applications/downloads/data/**theme.xml**
Строка **1736** вместо ключа **{lang="follow_type_immediate_change"}** прописан текст.

Сообщите куда следует.

![2021-03-23_08-37-59](https://user-images.githubusercontent.com/22107941/112098757-5ff17a80-8bb3-11eb-81cc-da850b89ed9e.png)
![2021-03-23_08-35-41](https://user-images.githubusercontent.com/22107941/112098478-e9ed1380-8bb2-11eb-8cce-7a4cc089818c.png)

**Comment by ilyahoilik** [comment]
Сообщил
