### ISSUE TITLE
"мы удалим вам email-адрес"

### ISSUE THREAD

**Issue by Tigla** [ipshelp/russian-language#273]
В футере письма есть такая строка:

> Если вы не предпримите никаких действий, мы удалим вам email-адрес и не будем связываться с вами. Нет необходимости отписываться. 

Там опечатка "ваш email-адрес"

**Comment by rvalitov** [comment]
`unsubscribe_not_needed`
Предлагаю так:
Если вы не предпримете никаких действий, мы удалим ваш адрес электронной почты и больше не будем связываться с вами. Отписываться нет необходимости.
